title: Theo Acquah, Data Analyst (Python & SQL)
#logo: /assets/img/head_cricle.png
logo: images/Theo 2.jpg
description: A portfolio of data science projects by Theo Acquah.
show_downloads: false
theme: jekyll-theme-minimal
