title: Theo Acquah, Data Analyst (Python & SQL)
#logo: /assets/img/head_cricle.png
logo: images/Theo.jpg
description: A portfolio of data science projects by Theo Acquah, demonstrating expertise in data wrangling, analysis, machine learning, and predictive modeling.
show_downloads: false
theme: jekyll-theme-minimal
